src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/model/Account.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.TableGenerator;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Justyna Małgorzaciak
 */
@TableGenerator(name = "AccountIdGen", table = "GENERATOR", pkColumnName = "ENTITY_NAME", valueColumnName = "ID_RANGE", pkColumnValue = "Account", initialValue=100)
@Entity
@DiscriminatorColumn(name = "type")
@DiscriminatorValue("ACCOUNT")
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE, generator="AccountIdGen")    
    @Column(name = "id")
    private Long id;
    
    @OneToOne
    @PrimaryKeyJoinColumn
    private Employee employee;
          
    @NotNull
    @Column(name = "employee_id", unique = true)
    private Long employeeId;
    
    @Version
    @Column(name = "version")
    private Long version;
    
    @Column(name = "login", nullable = false, unique = true)
    @Size(min = 5, max = 20)
    private String login;
    
    @Column(name = "password", nullable = false)
    @Size(min = 5, max = 20)
    private String password;
    
    @Column(name = "department")
    private AccessLevel department;
    
    @Column(name = "type")
    private String type;
    
    @OneToMany(mappedBy = "account")
    private List<Invoice> invoices = new ArrayList<Invoice>();

    public List<Invoice> getInvoices() {
        return invoices;
    }

    public void setInvoices(List<Invoice> invoices) {
        this.invoices = invoices;
    }

    
    public Long getId() {
        return id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public AccessLevel[] getAccessLevels() {
    return AccessLevel.values();
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public AccessLevel getDepartment() {
        return department;
    }

    public void setDepartment(AccessLevel department) {
        this.department = department;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Account)) {
            return false;
        }
        Account other = (Account) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return getLogin() + "." + getType();
    }
    
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/account/AccountController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.account;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.AccountEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Employee;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.utils.ContextUtils;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named("accountSession")
public class AccountController implements Serializable {

    @EJB
    AccountEndpoint accountEndpoint;

    private Employee editedAccount;

    public Employee getEditedAccount() {
        return editedAccount;
    }

    public void editAccount() {
        accountEndpoint.editAccount(editedAccount);
    }

    public void getAccountToEdition(Employee employee) {
        editedAccount = accountEndpoint.getAccountToEdition(employee);
    }

    public void removeAccount() {
        accountEndpoint.removeAccount(editedAccount);
    }

    public String registrateSession() {
        ContextUtils.invalidateSession();
        return "main";
    }

    public String getLogin() {
        return ContextUtils.getUserName();
    }
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/account/CreateAccountPageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.account;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.AccountDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.EmployeeDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.AccountEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.exception.AccountException;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Account;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.utils.ContextUtils;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "createAccountPageBean")
public class CreateAccountPageBean implements Serializable{
    
    @Inject
    AccountEndpoint accountEndpoint;
    
    private EmployeeDTO employeeDto;
    
    private AccountDTO accountDto;
    
    private static final Logger LOG = Logger.getLogger(CreateAccountPageBean.class.getName());

    public CreateAccountPageBean() {
      accountDto = new AccountDTO();
      employeeDto = new EmployeeDTO();
      
    }
   public String createAccount(){
        List<Account> listAccounts = accountEndpoint.getAccounts();
        try {
            for (Account listAccount : listAccounts) {
                if (listAccount.getLogin().equals(accountDto.getLogin())) {
                    throw new AccountException("Konto z takim loginem juz istnieje!");
                }
            }
            accountEndpoint.createAccount(accountDto, employeeDto);
            accountDto = new AccountDTO();

        } catch (AccountException ae) {
            LOG.log(Level.SEVERE, "Zgłoszenie w metodzie akcji wyjatku: ", ae);
            ContextUtils.emitInternationalizedMessage("createAccount:login", ae.getMessage());
            return null;
        }
        return "successAccount";
   }

    public EmployeeDTO getEmployeeDto() {
        return employeeDto;
    }

    public void setEmployeeDto(EmployeeDTO employeeDto) {
        this.employeeDto = employeeDto;
    }

    public AccountDTO getAccountDto() {
        return accountDto;
    }

    public void setAccountDto(AccountDTO accountDto) {
        this.accountDto = accountDto;
    }
    
    public String returnToAccountsList(){
        return "accountsList";
    }
   
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/account/EditAccountPageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.account;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.AccountDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.AccountEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.utils.ContextUtils;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Account;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Employee;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "editAccountPageBean")
public class EditAccountPageBean implements Serializable {

    @Inject
    AccountController accountController;

    @EJB
    AccountEndpoint accountEndpoint;

    private AccountDTO accountDto;

    public EditAccountPageBean() {
        accountDto = new AccountDTO();
    }

    public String editAccount() {
        accountController.editAccount();
        return "successEditAccount";
    }

    public Employee getEmployee() {
        return accountController.getEditedAccount();
    }

    public String editPassword() {
        Account account = accountEndpoint.getMyAccountToEdition();
        if (!account.getPassword().equals(accountDto.getPassword())) {
            ContextUtils.emitInternationalizedMessage("changePassword:oldPassword", "Hasło różni się od obecnego!");
            return null;
        } else if (!accountDto.getNewPassword().equals(accountDto.getConfirmedPassword())) {
            ContextUtils.emitInternationalizedMessage("changePassword:newPassword", "Potwierdzone hasło różni się od nowego hasła!");
            return null;
        } else if (accountDto.getPassword().equals(accountDto.getNewPassword())) {
            ContextUtils.emitInternationalizedMessage("changePassword:newPassword", "Hasło nie może być identyczne jak poprzednie!");
            return null;}
            else {
        accountEndpoint.editMyAccount(accountDto, account);
        return "changePasswordSuccess";}
    }

    public AccountDTO getAccountDto() {
        return accountDto;
    }

    public void setAccountDto(AccountDTO accountDto) {
        this.accountDto = accountDto;
    }

}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/account/ListAccountsPageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.account;

import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.AccountEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Account;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Employee;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "listAccountsPageBean")
public class ListAccountsPageBean implements Serializable {

    @Inject
    AccountEndpoint accountEndpoint;

    @Inject
    AccountController accountController;

    public List<Account> getAccounts() {
        return accountEndpoint.getAccounts();
    }

    public List<Employee> getEmployees() {
        return accountEndpoint.getEmployees();
    }

    public String editAccount(Employee employee) {
        accountController.getAccountToEdition(employee);
        return "editAccount";
    }

    public String removeAccount(Employee employee) {
        accountController.getAccountToEdition(employee);
        accountController.removeAccount();
        return "accountsList";
    }
}

src/main/webapp/accounts/accountsList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/main/template.xhtml">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <br />
        <h1><center>Lista kont</center></h1>
        <br />
        <h:form>
            <h:dataTable style="margin-left: 330px" value="#{listAccountsPageBean.employees}" var="employee" border="5">
                <h:column>
                    <f:facet name="header" >L.p.</f:facet>
                        #{listAccountsPageBean.employees.indexOf(employee) + 1}.
                </h:column>
                <h:column>
                    <f:facet name="header" >Imię</f:facet>
                        #{employee.firstName}

                </h:column>
                <h:column>
                    <f:facet name="header" >Nazwisko</f:facet>
                        #{employee.lastName}

                </h:column>
                <h:column>
                    <f:facet name="header" >PESEL</f:facet>
                        #{employee.pesel}

                </h:column>
                <h:column>
                    <f:facet name="header" >Email</f:facet>
                        #{employee.email}

                </h:column>                
                <h:column>
                    <f:facet name="header" >Telefon</f:facet>
                        #{employee.telephone}
                </h:column>
                <h:column>
                    <f:facet name="header" >Dostępne akcje</f:facet>
                    <h:commandButton value="Edytuj" action="#{listAccountsPageBean.editAccount(employee)}" />
                    <h:commandButton value="Usuń" action="#{listAccountsPageBean.removeAccount(employee)}" />
                </h:column>
            </h:dataTable>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/accounts/createAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                template="/main/template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form id="createAccount">
            <br />
            <h1><center>Nowe konto</center></h1>
            <br />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Imię:  " />
            <h:inputText style="margin-left: 34px" id="firstName" value="#{createAccountPageBean.employeeDto.firstName}" maxlength="120" required="true" /> &nbsp; <h:message for="firstName" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Nazwisko:  " />
            <h:inputText id="lastName" value="#{createAccountPageBean.employeeDto.lastName}" maxlength="120" required="true"/> &nbsp; <h:message for="lastName" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  PESEL:  " />
            <h:inputText style="margin-left: 16px"  id="pesel" value="#{createAccountPageBean.employeeDto.pesel}" maxlength="11" required="true" validatorMessage="Numer PESEL powinien składać się z 11 cyfr">
                <f:validateRegex pattern=".{11,}"/> 
            </h:inputText> &nbsp; <h:message for="pesel" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  E-mail:  " />
            <h:inputText style="margin-left: 20px" id="email" value="#{createAccountPageBean.employeeDto.email}" maxlength="50"> 
            </h:inputText> &nbsp; <h:message for="email" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Telefon:  " />
            <h:inputText style="margin-left: 14px" id="telephone" value="#{createAccountPageBean.employeeDto.telephone}" maxlength="11" validatorMessage="Numer telefonu powinien zawierać od 7 do 11 cyfr"> 
                  <f:validateRegex pattern=".{7,}"/> 
            </h:inputText> &nbsp; <h:message for="telephone" style="color:red" />
            <br />
            <br />
            <br />
            <h2 style="margin-left: 330px">  Uwierzytelnienie</h2>
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Login:  " />
            <h:inputText style="margin-left: 27px" id="login" value="#{createAccountPageBean.accountDto.login}" maxlength="20" required="true" validatorMessage="Login powinien zawierać od 5 do 20 znaków"> 
                  <f:validateRegex pattern=".{5,}"/> 
            </h:inputText> &nbsp; <h:message for="login" style="color:red" />

            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Hasło:  " />
            <h:inputSecret style="margin-left: 28px;" id="password" value="#{createAccountPageBean.accountDto.password}" maxlength="20" required="true" validatorMessage="Hasło powinno zawierać od 5 do 20 znaków"> 
                  <f:validateRegex pattern=".{5,}"/> 
            </h:inputSecret> &nbsp; <h:message for="password" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Typ konta:  " />
            <h:selectOneMenu value="#{createAccountPageBean.accountDto.department}">
            <f:selectItems value="#{createAccountPageBean.accountDto.accessLevels}" />
            </h:selectOneMenu> &nbsp; <h:message for="type" style="color:red" />
            <br />
            <br />
            <h:commandButton style="margin-left: 20px" value="Utwórz" action="#{createAccountPageBean.createAccount()}"/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/accounts/editAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                template="/main/template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
            <br />
            <h1><center>Edytuj konto</center></h1>
            <br />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Imię:  " />
            <h:inputText style="margin-left: 34px" id="firstName" value="#{editAccountPageBean.employee.firstName}" maxlength="120" required="true" /> &nbsp; <h:message for="firstName" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Nazwisko:  " />
            <h:inputText id="lastName" value="#{editAccountPageBean.employee.lastName}" maxlength="120" required="true"/> &nbsp; <h:message for="lastName" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  PESEL:  " />
            <h:inputText style="margin-left: 16px" id="pesel" value="#{editAccountPageBean.employee.pesel}" required="true" validatorMessage="Numer PESEL powinien składać się z 11 cyfr">
                <f:validateRegex pattern=".{11,}"/> 
            </h:inputText> &nbsp; <h:message for="pesel" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  E-mail:  " />
            <h:inputText style="margin-left: 20px" id="email" value="#{editAccountPageBean.employee.email}" maxlength="50"> 
            </h:inputText> &nbsp; <h:message for="email" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Telefon:  " />
            <h:inputText style="margin-left: 14px" id="telephone" value="#{editAccountPageBean.employee.telephone}" maxlength="11" validatorMessage="Numer telefonu powinien zawierać od 7 do 11 cyfr"> 
                  <f:validateRegex pattern=".{7,}"/> 
            </h:inputText> &nbsp; <h:message for="telephone" style="color:red" />
            <br />
            <br />
            <h:commandButton style="margin-left: 20px;" value="Edytuj" action="#{editAccountPageBean.editAccount()}"/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/accounts/successAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/main/template.xhtml">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
        <br />
        <p style="margin-left: 330px">Nowe konto zostało utworzone!</p>
        <br />
        <h:commandButton style="margin-left: 20px" value="Pokaż listę kont" action="#{createAccountPageBean.returnToAccountsList()}"/>
        </h:form>
    </ui:define>
    <br />

</ui:composition>

src/main/webapp/accounts/successEditAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/main/template.xhtml">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
        <br />
        <p style="margin-left: 330px">Konto zostało edytowane!</p><br />
        <h:commandButton style="margin-left: 20px" value="Powróć do listy kont" action="#{createAccountPageBean.returnToAccountsList()}"/>
        </h:form>
    </ui:define>
    <br />

</ui:composition>