src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/invoice/CreateInvoicePageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.invoice;

import java.io.Serializable;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.ArticleDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.InvoiceDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.VendorDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.ArticleEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.utils.ContextUtils;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.InvoiceEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.exception.ArticleException;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.exception.BaseException;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.exception.InvoiceException;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Article;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Invoice;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "createPageBean")
public class CreateInvoicePageBean implements Serializable {

    @Inject
    private InvoiceEndpoint invoiceEndpoint;

    @Inject
    private ArticleEndpoint articleEndpoint;

    private InvoiceDTO invoice;

    private ArticleDTO articleDto;

    private VendorDTO vendorDto;

    private static final Logger LOG = Logger.getLogger(CreateInvoicePageBean.class.getName());

    public String addArticle() {

        try {
            if (articleDto.getNameOfArticle() == null) {
                throw new ArticleException("Wpisz nazwę artykułu, zanim go dodasz!");
            }
            
            articleEndpoint.addArticle(articleDto, invoice);
            articleDto = new ArticleDTO();
        } catch (ArticleException ae) {
            LOG.log(Level.SEVERE, "Zgłoszenie w metodzie akcji wyjatku: ", ae);
            ContextUtils.emitInternationalizedMessage("createInvoice:nameOfArticle", ae.getMessage());
            return null;
        }
        return "createInvoiceArticleAdded";
    }

    public ArticleDTO getArticleDto() {
        return articleDto;
    }

    public void setArticleDto(ArticleDTO articleDto) {
        this.articleDto = articleDto;
    }

    public List<Article> getArticles() {
        return articleEndpoint.getArticles(invoice);
    }

    public VendorDTO getVendorDto() {
        return vendorDto;
    }

    public void setVendorDto(VendorDTO vendorDto) {
        this.vendorDto = vendorDto;
    }

    public InvoiceDTO getInvoice() {
        return invoice;
    }

    public void setInvoiceDto(InvoiceDTO invoice) {
        this.invoice = invoice;
    }

    public CreateInvoicePageBean() {
        invoice = new InvoiceDTO();
        articleDto = new ArticleDTO();
        vendorDto = new VendorDTO();
    }

    public String createInvoice() throws BaseException, ParseException {

        List<Invoice> listInvoices = invoiceEndpoint.getInvoices();
        try {
            for (Invoice listInvoice : listInvoices) {
                if (listInvoice.getNumber().equals(invoice.getNumber())) {
                    throw new InvoiceException("Faktura z takim numerem juz istnieje!");
                }
            }
            if(articleEndpoint.getArticles(invoice).isEmpty()){
                throw new ArticleException("Przed utworzeniem faktury dodaj przynajmniej jeden artykuł!");
            }
            invoiceEndpoint.createNewInvoice(invoice, vendorDto);
            invoice = new InvoiceDTO();
            articleDto = new ArticleDTO();
            vendorDto = new VendorDTO();
        } catch (InvoiceException ie) {
            LOG.log(Level.SEVERE, "Zgłoszenie w metodzie akcji wyjatku: ", ie);
            ContextUtils.emitInternationalizedMessage("createInvoice:number", ie.getMessage());
            return null;
        }
          catch (ArticleException ae) {
            LOG.log(Level.SEVERE, "Zgłoszenie w metodzie akcji wyjatku: ", ae);
            ContextUtils.emitInternationalizedMessage("createInvoice:nameOfArticle", ae.getMessage());
            return null;
        }
        return "successInvoice";
    }

    public String returnToInvoicesList() {
        return "newInvoices";
    }
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/invoice/EditInvoicePageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.invoice;

import java.io.Serializable;
import java.text.ParseException;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.dto.ArticleDTO;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.ArticleEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Article;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Invoice;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Vendor;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "editPageBean")
public class EditInvoicePageBean implements Serializable {

    @Inject
    private ArticleEndpoint articleEndpoint;

    @Inject
    private InvoiceController invoiceController;

    @Inject
    private VendorController vendorController;
    
    private ArticleDTO articleDto;

    public EditInvoicePageBean() {
        articleDto = new ArticleDTO();
    }

    public Invoice getInvoice() {
        return invoiceController.getEditedInvoice();
    }

    public String editInvoice() throws ParseException {
        
        invoiceController.editInvoice();
        vendorController.editVendor();
        articleDto = new ArticleDTO();
        return "successEditInvoice";
    }
    
    public String cancelInvoice() throws ParseException{
        invoiceController.editInvoice();
        return "successCancel";
    }
    
    public Vendor getVendor(){
        return vendorController.getEditedVendor();
    }

    public String addArticle() {

        articleEndpoint.addArticle(articleDto, invoiceController.getEditedInvoice());
        articleDto = new ArticleDTO();
        return "editInvoice";
    }

    public ArticleDTO getArticleDto() {
        return articleDto;
    }

    public void setArticleDto(ArticleDTO articleDto) {
        this.articleDto = articleDto;
    }

    public List<Article> getArticles() {
        return articleEndpoint.getArticles(invoiceController.getEditedInvoice());
    }
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/invoice/InvoiceController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.invoice;

import java.io.Serializable;
import java.text.ParseException;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.InvoiceEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.exception.InvoiceException;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Invoice;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
public class InvoiceController implements Serializable {
    
    private Invoice editedInvoice;
    
    @EJB
    InvoiceEndpoint invoiceEndpoint;
    
     public void getInvoiceToEdition(Invoice invoice) {
      editedInvoice = invoiceEndpoint.getInvoiceToEdition(invoice);
    }
    
    public Invoice getEditedInvoice(){
        return editedInvoice;
    }
    
    public void editInvoice() throws ParseException{
        invoiceEndpoint.editInvoice(editedInvoice);
    }
    
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/invoice/ListInvoicePageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.invoice;

import java.io.Serializable;
import java.text.ParseException;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.DataModel;
import javax.inject.Inject;
import javax.inject.Named;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.InvoiceEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Invoice;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
@Named(value = "listPageBean")
public class ListInvoicePageBean implements Serializable {

    @Inject
    private InvoiceEndpoint invoiceEndpoint;

    @Inject
    private InvoiceController invoiceController;

    @Inject
    private VendorController vendorController;

    DataModel<Invoice> invoicesDataModel;

    public List<Invoice> getInvoices() {
        return invoiceEndpoint.getInvoices();
    }

    public List<Invoice> getNewInvoices() {
        return invoiceEndpoint.getNew();
    }

    public List<Invoice> getInvoicesInProcess() {
        return invoiceEndpoint.getInProcess();
    }

    public List<Invoice> getAcceptedInvoices() {
        return invoiceEndpoint.getAccepted();

    }

    public List<Invoice> getCancelledInvoices() {
        return invoiceEndpoint.getCancelled();
    }

    public String editInvoice(Invoice invoice) {
        invoiceController.getInvoiceToEdition(invoice);
        vendorController.getVendorToEdition(invoice);
        return "editInvoice";
    }

    public String editCancelledInvoice(Invoice invoice) {
        invoiceController.getInvoiceToEdition(invoice);
        vendorController.getVendorToEdition(invoice);
        return "editInvoiceAfterCancelled";
    }

    public String cancelInvoice(Invoice invoice) throws ParseException {
        invoiceEndpoint.cancelInvoice(invoice);
        invoiceController.getInvoiceToEdition(invoice);
        return "beforeInvoiceCancelled";
    }

    public String sendInvoice(Invoice invoice) throws ParseException {
        invoiceEndpoint.sendInvoice(invoice);
        return "newInvoices";
    }

    public String acceptInvoice(Invoice invoice) throws ParseException {
        invoiceEndpoint.acceptInvoice(invoice);
        return "acceptedInvoices";
    }

    public String returnToMainPage() {
        return "main";
    }
}

src/main/java/pl/lodz/p/it/spjava/purchaseinvoicessystem/web/invoice/VendorController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.lodz.p.it.spjava.purchaseinvoicessystem.web.invoice;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.ejb.endpoint.InvoiceEndpoint;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Invoice;
import pl.lodz.p.it.spjava.purchaseinvoicessystem.model.Vendor;

/**
 *
 * @author Justyna Małgorzaciak
 */
@SessionScoped
public class VendorController implements Serializable{
    
    private Vendor editVendor;
            
    @EJB
    InvoiceEndpoint invoiceEndpoint;
    
     public void getVendorToEdition(Invoice invoice) {
      editVendor = invoiceEndpoint.getVendorToEdition(invoice);
    }
    
    public Vendor getEditedVendor(){
        return editVendor;
    }
    
    public void editVendor(){
        invoiceEndpoint.editVendor(editVendor);
    }
    
}

src/main/webapp/invoices/editInvoice.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                template="/main/template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h1><center>Faktura VAT</center></h1>
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Numer faktury:  " />&nbsp;&nbsp;
            <h:outputText style="font-weight: bold;" id="number" value="#{editPageBean.invoice.number}"/> 

            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Data faktury:  " />
            <h:inputText id="dateOfInvoice" value="#{editPageBean.invoice.dateOfInvoice}" maxlength="400" required="true" validatorMessage="Data faktury: poprawny format daty to dd/mm/rrrr">

                <f:validateRegex pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}"/> 

            </h:inputText>

            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Data płatności:  " />
            <h:inputText id="dateOfPayment" value="#{editPageBean.invoice.dateOfPayment}" maxlength="400" required="true" validatorMessage="Data płatności: poprawny format daty to dd/mm/rrrr">

                <f:validateRegex pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}"/> 

            </h:inputText>
            <br />
            <h:message style="margin-left: 20px; text-align: center; color:red" for="number" /> &nbsp; <h:message for="dateOfInvoice" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="dateOfPayment" style="margin-left: 20px; text-align: center; color:red" />
            <br />
            <h2 style="margin-left: 400px;">Dostawca</h2>
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Nazwa:  " />
            <h:inputText id="name" value="#{editPageBean.vendor.name}"/> &nbsp; <h:message for="name" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Adres:  " />
            <h:inputText style="margin-left: 6px" id="address"  value="#{editPageBean.vendor.address}" /> &nbsp; <h:message for="address" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Kraj:  " />
            <h:inputText style="margin-left: 16px" id="country"  value="#{editPageBean.vendor.country}" /> &nbsp; <h:message for="country" style="color:red" />
            <br /> 
            <br />
            <h2 style="margin-left: 400px;">  Artykuły</h2>

            <h:dataTable style="margin-left: 330px" value="#{editPageBean.articles}" var="article" border="5">
                <h:column>
                    <f:facet name="header" >Numer</f:facet>
                    #{editPageBean.articles.indexOf(article) + 1}.
                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Nazwa artykułu</f:facet>
                    #{article.nameOfArticle}
                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Cena za sztukę</f:facet>
                    #{article.price} zł
                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Ilość</f:facet>
                    #{article.quantityOfArticles} szt.
                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Cena netto</f:facet>
                    #{article.totalNetPrice} zł
                    
                </h:column>                
                <h:column>
                    <f:facet name="header" >Stopa podatkowa</f:facet>
                    #{article.taxRate}%
                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Cena brutto</f:facet>
                    #{article.totalGrossPrice} zł
                    
                </h:column>
            </h:dataTable>
            <br />
            <table style="margin-left: 330px" border="5">
                <tr>
                    <td>Nazwa artykułu</td><td>Cena za sztukę</td><td>Ilość</td><td>Stopa podatkowa</td>
                </tr>
                <tr>
                    <td><h:inputText id="nameOfArticle" value="#{editPageBean.articleDto.nameOfArticle}" maxlength="300" required="false" ></h:inputText></td> 
                    <td><h:inputText id="price" value="#{editPageBean.articleDto.price}" maxlength="20" required="false" validatorMessage="Cena: wartość nie może być mniejsza od 0"><f:validateDoubleRange minimum="0"/></h:inputText></td> 
                    <td><h:inputText id="quantityOfArticle" value="#{editPageBean.articleDto.quantityOfArticles}" maxlength="20" required="false" validatorMessage="Ilość: ilość nie może być mniejsza od 1"><f:validateDoubleRange minimum="1"/></h:inputText></td>
                    <td><h:inputText id="tax" value="#{editPageBean.articleDto.taxForArticle}" maxlength="5" required="false" validatorMessage="Podatek: wartość nie może być mniejsza od 0 i większa od 100"><f:validateDoubleRange minimum="0" maximum="100"/></h:inputText></td>
                    <td><h:commandButton value="Dodaj artykuł do faktury" action="#{editPageBean.addArticle()}"/></td>
                </tr>
            </table>
             <h:message for="nameOfArticle" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="price" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="quantityOfArticle" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="tax" style="margin-left: 20px; text-align: center; color:red"/>
            <br />
            <br />
            <p style="margin-left: 325px; color: red; font-weight: bold;" >Udokumentuj w komentarzu, co zostało zmienione</p>
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Komentarz:  " />
            <h:inputText id = "comment" style="width:738px;height:25px" value="#{editPageBean.invoice.comment}" maxlength="10000" validatorMessage="Napisz, co zostało zmienione w powyższym dokumencie" ><f:validateRequired /></h:inputText><br /> <h:message style="margin-left: 20px; text-align: center; color:red" for="comment"/>
            <br /> 
            <br />
            <br />
            <h:commandButton style="margin-left: 20px" value="Edytuj" action="#{editPageBean.editInvoice()}"/>
            <h:commandButton style="margin-left: 20px" value="Powróć" action="#{listPageBean.returnToMainPage()}"/>
        </h:form>
    </ui:define>
    
</ui:composition>

src/main/webapp/invoices/editInvoiceAfterCancelled.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                template="/main/template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h1><center>Faktura VAT</center></h1>
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Numer faktury:  " />&nbsp;&nbsp;
            <h:outputText style="font-weight: bold;" id="number" value="#{editPageBean.invoice.number}"/> 

            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Data faktury:  " />
            <h:inputText id="dateOfInvoice" value="#{editPageBean.invoice.dateOfInvoice}" maxlength="400" required="true" validatorMessage="Data faktury: poprawny format daty to dd/mm/rrrr">

                <f:validateRegex pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}"/> 

            </h:inputText>

            <h:outputLabel style="margin-left: 20px; text-align: center"  value="  Data płatności:  " />
            <h:inputText id="dateOfPayment" value="#{editPageBean.invoice.dateOfPayment}" maxlength="400" required="true" validatorMessage="Data płatności: poprawny format daty to dd/mm/rrrr">

                <f:validateRegex pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}"/> 

            </h:inputText>
            <br />
            <h:message style="margin-left: 20px; text-align: center; color:red" for="number" /> &nbsp; <h:message for="dateOfInvoice" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="dateOfPayment" style="margin-left: 20px; text-align: center; color:red" />
            <br />
            <h2 style="margin-left: 400px;">Dostawca</h2>
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Nazwa:  " />
            <h:inputText id="name" value="#{editPageBean.vendor.name}"/> &nbsp; <h:message for="name" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Adres:  " />
            <h:inputText style="margin-left: 6px" id="address"  value="#{editPageBean.vendor.address}" /> &nbsp; <h:message for="address" style="color:red" />
            <br />
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Kraj:  " />
            <h:inputText style="margin-left: 16px" id="country"  value="#{editPageBean.vendor.country}" /> &nbsp; <h:message for="country" style="color:red" />
            <br /> 
            <br />
            <h2 style="margin-left: 400px;">  Artykuły</h2>

            <h:dataTable style="margin-left: 330px" value="#{editPageBean.articles}" var="article" border="5">
                <h:column>
                    <f:facet name="header" >Numer</f:facet>
                    #{editPageBean.articles.indexOf(article) + 1}.

                </h:column>
                <h:column>
                    <f:facet name="header" >Nazwa artykułu</f:facet>
                        #{article.nameOfArticle}

                </h:column>
                <h:column>
                    <f:facet name="header" >Cena za sztukę</f:facet>
                    #{article.price} zł

                </h:column>
                <h:column>
                    <f:facet name="header" >Ilość</f:facet>
                    #{article.quantityOfArticles} szt.

                </h:column>
                <h:column>
                    <f:facet name="header" >Cena netto</f:facet>
                    #{article.totalNetPrice} zł

                </h:column>                
                <h:column>
                    <f:facet name="header" >Stopa podatkowa</f:facet>
                    #{article.taxRate}%

                </h:column>
                <h:column>
                    <f:facet name="header" >Cena brutto</f:facet>
                    #{article.totalGrossPrice} zł

                </h:column>
            </h:dataTable>
            <br />
            <table style="margin-left: 330px" border="5">
                <tr>
                    <td>Nazwa artykułu</td><td>Cena za sztukę</td><td>Ilość</td><td>Stopa podatkowa</td>
                </tr>
                <tr>
                    <td><h:inputText id="nameOfArticle" value="#{editPageBean.articleDto.nameOfArticle}" maxlength="300" required="false" ></h:inputText></td> 
                    <td><h:inputText id="price" value="#{editPageBean.articleDto.price}" maxlength="20" required="false" validatorMessage="Cena: wartość nie może być mniejsza od 0"><f:validateDoubleRange minimum="0"/></h:inputText></td> 
                    <td><h:inputText id="quantityOfArticle" value="#{editPageBean.articleDto.quantityOfArticles}" maxlength="20" required="false" validatorMessage="Ilość: ilość nie może być mniejsza od 1"><f:validateDoubleRange minimum="1"/></h:inputText></td>
                    <td><h:inputText id="tax" value="#{editPageBean.articleDto.taxForArticle}" maxlength="5" required="false" validatorMessage="Podatek: wartość nie może być mniejsza od 0 i większa od 100"><f:validateDoubleRange minimum="0" maximum="100"/></h:inputText></td>
                    <td><h:commandButton value="Dodaj artykuł do faktury" action="#{editPageBean.addArticle()}"/></td>
                </tr>
            </table>
            <h:message for="nameOfArticle" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="price" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="quantityOfArticle" style="margin-left: 20px; text-align: center; color:red" /> &nbsp; <h:message for="tax" style="margin-left: 20px; text-align: center; color:red"/>
            <br />
            <br />
            <p style="margin-left: 325px; color: red; font-weight: bold;" >Udokumentuj w komentarzu, co zostało zmienione</p>
            <h:outputLabel style="margin-left: 20px; text-align: center" value="  Komentarz:  " />
            <h:inputText id = "comment" style="width:738px;height:25px" value="#{editPageBean.invoice.comment}" maxlength="10000" required="true" validatorMessage="Napisz, co zostało zmienione w powyższym dokumencie" ><f:validateRequired /></h:inputText><br /> <h:message style="margin-left: 20px; text-align: center; color:red" for="comment"/>
            <br />
            <p style="margin-left: 325px; color: red; font-weight: bold;" >Powód odrzucenia faktury</p>
            <h:outputLabel style="margin-left: 20px; text-align: center" value=" Uzasadnienie:  " />
            <h:outputText id = "reason" style="width:738px;height:25px" value="#{editPageBean.invoice.reasonBeforeCancelled}"/>
            <br /> 
            <br />
            <h:commandButton style="margin-left: 20px" value="Edytuj" action="#{editPageBean.editInvoice()}"/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/invoices/successCancel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/main/template.xhtml">

    <ui:define name="top">
    </ui:define>

    <ui:define name="left">
        <ui:include src="/main/menu.xhtml" />
    </ui:define>

    <ui:define name="content">
        <h:form>
        <br />
        <p style="margin-left: 330px">Faktura została odrzucona i powróciła do działu administracji</p>
        <br />
        <h:commandButton style="margin-left: 20px" value="Powróć do strony głównej" action="#{listPageBean.returnToMainPage()}"/>
        </h:form>
    </ui:define>
    <br />

</ui:composition>